ALTER SESSION SET CONTAINER=FREEPDB1 SERVICE=FREEpdb1;

CREATE USER APP IDENTIFIED BY "APPPW" QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SYNONYM TO APP;


